on:
  push:

jobs:
  upload_to_gcs:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Must come first!
        
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: $PROJECT_ID
          workload_identity_provider: $PROVIDER_FULL_PATH

      - name: Generate file
        id: generate_file
        run: |
          CURRENT_FILE="$(date +"%Y-%m-%d").txt"
          echo "FILENAME=$CURRENT_FILE" >> $GITHUB_OUTPUT
          touch "$CURRENT_FILE"
          
      - name: Upload file to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ${{ steps.generate_file.outputs.FILENAME }} 
          destination: $BUCKET_NAME


