on:
  push:

jobs:
 job_id:
    # Add "id-token" with the intended permissions.
   permissions:
     contents: 'read'
     id-token: 'write'

   steps:
   - uses: 'actions/checkout@v4' # Must come first!
   - uses: 'google-github-actions/auth@v2'
     with:
      project_id: 'vertex-llm-finetune' #TODO: change me
      workload_identity_provider: "projects/7029402384/locations/global/workloadIdentityPools/github/providers/my-repo" 

    - name: Generate file
      run: |
        CURRENT_DATE=$(date +"%Y-%m-%d")
        echo "$CURRENT_DATE" > file.txt 

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'file.txt'
        destination: 'bucket-for-storing-embeddings'

